REChase/REChase/REChase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teams.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

REChase/REChase/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teams.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

if True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

REChase/bit1/urls.py
from django.urls import path
from . import views

app_name = 'bit1'
urlpatterns = [
    path('', views.home, name='home'),
]

REChase/prefixSum/urls.py
from django.urls import path
from . import views

app_name = 'prefixSum'
urlpatterns = [
    path('', views.home, name='home'),
    path('firstTime/', views.firstTime, name='firstTime'),
]

REChase/REChase/prefixSum/models.py
from django.db import models


class PrefixSum(models.Model):
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    accuracy = models.FloatField(default=0)
    modal = models.TextField(null=True, blank=True)
    modal1 = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'That question regarding prefix sum encoding'

    def calcAccu(self):
        self.accuracy = round(self.correct / (float(self.correct + self.wrong)), 2) * 100

    def answered(self, right=1):
        if right:
            self.correct = self.correct + 1
        else:
            self.wrong = self.wrong + 1
        self.calcAccu()
        self.save()


class Used(models.Model):
    word = models.CharField(max_length=12, unique=True)

REChase/prefixSum/models.py
from django.db import models


class PrefixSum(models.Model):
    correct = models.IntegerField(default=0)
    wrong = models.IntegerField(default=0)
    accuracy = models.FloatField(default=0)
    modal = models.TextField(null=True, blank=True)
    modal1 = models.TextField(null=True, blank=True)

    def __str__(self):
        return 'That question regarding prefix sum encoding'

    def calcAccu(self):
        self.accuracy = round(self.correct / (float(self.correct + self.wrong)), 2) * 100

    def answered(self, right=1):
        if right:
            self.correct = self.correct + 1
        else:
            self.wrong = self.wrong + 1
        self.calcAccu()
        self.save()


class Used(models.Model):
    word = models.CharField(max_length=12, unique=True)

REChase/REChase/prefixSum/forms.py
from django import forms


class answerForm(forms.Form):
    answer = forms.CharField(max_length=40, required=True)


class SampleForm(forms.Form):
    sample = forms.CharField(min_length=8, max_length=12, required=True)

REChase/prefixSum/forms.py
from django import forms


class answerForm(forms.Form):
    answer = forms.CharField(max_length=40, required=True)


class SampleForm(forms.Form):
    sample = forms.CharField(min_length=8, max_length=12, required=True)

REChase/REChase/prefixSum/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from teams.decorators import team_required
from teams.models import Team, Player
from .forms import answerForm, SampleForm
from .models import PrefixSum, Used
from .utils import solve, func

THIS_LEVEL = 8


@login_required
@team_required
def home(request):
    context = {}
    user = request.user
    profile = Player.objects.get(user=user)
    team = Team.objects.get(id=profile.team.pk)

    if team.current_level != THIS_LEVEL:
        return redirect(reverse_lazy('teams:get-level'))

    question = PrefixSum.objects.first()

    if team.current_question == -1:
        return redirect('teams:prefixSum:firstTime')

    answer = answerForm(request.POST or None)
    context['team'] = team
    context['profile'] = profile
    sample_name, name = str(team.question).split(',')
    context['sample_name'] = sample_name
    context['sample_ans'] = solve(sample_name)
    context['name'] = name
    context['answer'] = answer
    context['question'] = question
    corr_ans = solve(name)
    if request.method == 'POST':
        if answer.is_valid():
            ans = answer.cleaned_data['answer'].upper()
            if corr_ans == ans:

                team.answerCorr(THIS_LEVEL, corr_ans)
                question.answered(right=1)
                return redirect(reverse_lazy('teams:get-level'))

            else:
                question.answered(right=0)
                context['wrong'] = 1

    return render(request, 'prefixSum/question.html', context=context)


@login_required
@team_required
def firstTime(request):
    context = {}
    user = request.user
    profile = Player.objects.get(user=user)
    team = Team.objects.get(id=profile.team.pk)

    if team.current_level != THIS_LEVEL:
        return redirect(reverse_lazy('teams:get-level'))

    context['profile'] = profile
    context['team'] = team
    if team.current_question != -1:
        return redirect('teams:prefixSum:home')

    sample = SampleForm(request.POST or None)
    context['sample'] = sample
    if request.method == 'POST':
        if sample.is_valid():
            sample_name = sample.cleaned_data['sample'].upper()
            if (not (7 < len(sample_name) < 13)) or any(map(lambda x: not 65 <= ord(x) <= 90, sample_name)):
                context['invalid'] = 1
                return render(request, 'prefixSum/firstTime.html', context=context)

            if len(set(list(sample_name))) <= 3:
                context['invalid_variation'] = 1
                return render(request, 'prefixSum/firstTime.html', context=context)

            qs = Used.objects.filter(word__exact=sample_name)
            if len(qs) != 0:
                context['repeat'] = 1
                return render(request, 'prefixSum/firstTime.html', context)
            else:
                obj = Used(word=sample_name)
                obj.save()
            context['sample_name'] = sample_name

            sample_ans = solve(sample_name)
            context['sample_ans'] = sample_ans
            name, ans = func(sample=0)
            team.question = ','.join((name, sample_name))
            team.current_question = 1
            team.save()
            return redirect('teams:prefixSum:home')

    return render(request, 'prefixSum/firstTime.html', context)

REChase/prefixSum/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from teams.decorators import team_required
from teams.models import Team, Player
from .forms import answerForm, SampleForm
from .models import PrefixSum, Used
from .utils import solve, func

THIS_LEVEL = 8


@login_required
@team_required
def home(request):
    context = {}
    user = request.user
    profile = Player.objects.get(user=user)
    team = Team.objects.get(id=profile.team.pk)

    if team.current_level != THIS_LEVEL:
        return redirect(reverse_lazy('teams:get-level'))

    question = PrefixSum.objects.first()

    if team.current_question == -1:
        return redirect('teams:prefixSum:firstTime')

    answer = answerForm(request.POST or None)
    context['team'] = team
    context['profile'] = profile
    sample_name, name = str(team.question).split(',')
    context['sample_name'] = sample_name
    context['sample_ans'] = solve(sample_name)
    context['name'] = name
    context['answer'] = answer
    context['question'] = question
    corr_ans = solve(name)
    if request.method == 'POST':
        if answer.is_valid():
            ans = answer.cleaned_data['answer'].upper()
            if corr_ans == ans:

                team.answerCorr(THIS_LEVEL, corr_ans)
                question.answered(right=1)
                return redirect(reverse_lazy('teams:get-level'))

            else:
                question.answered(right=0)
                context['wrong'] = 1

    return render(request, 'prefixSum/question.html', context=context)


@login_required
@team_required
def firstTime(request):
    context = {}
    user = request.user
    profile = Player.objects.get(user=user)
    team = Team.objects.get(id=profile.team.pk)

    if team.current_level != THIS_LEVEL:
        return redirect(reverse_lazy('teams:get-level'))

    context['profile'] = profile
    context['team'] = team
    if team.current_question != -1:
        return redirect('teams:prefixSum:home')

    sample = SampleForm(request.POST or None)
    context['sample'] = sample
    if request.method == 'POST':
        if sample.is_valid():
            sample_name = sample.cleaned_data['sample'].upper()
            if (not (7 < len(sample_name) < 13)) or any(map(lambda x: not 65 <= ord(x) <= 90, sample_name)):
                context['invalid'] = 1
                return render(request, 'prefixSum/firstTime.html', context=context)

            if len(set(list(sample_name))) <= 3:
                context['invalid_variation'] = 1
                return render(request, 'prefixSum/firstTime.html', context=context)

            qs = Used.objects.filter(word__exact=sample_name)
            if len(qs) != 0:
                context['repeat'] = 1
                return render(request, 'prefixSum/firstTime.html', context)
            else:
                obj = Used(word=sample_name)
                obj.save()
            context['sample_name'] = sample_name

            sample_ans = solve(sample_name)
            context['sample_ans'] = sample_ans
            name, ans = func(sample=0)
            team.question = ','.join((name, sample_name))
            team.current_question = 1
            team.save()
            return redirect('teams:prefixSum:home')

    return render(request, 'prefixSum/firstTime.html', context)

REChase/REChase/prefixSum/templates/prefixSum/firstTime.html
{% include 'teams/base_bootstrap.html' %}


{% block content %}
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Niconne&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Metrophobic&display=swap');

    input[type=submit] {
      background: -webkit-gradient(linear,left bottom, left top,from(#000000),to(#262626));
      background: -webkit-linear-gradient(bottom,#000000,#262626);
      background: -moz-linear-gradient(bottom,#000000,#262626);
      background: -o-linear-gradient(bottom,#000000,#262626);
      background: linear-gradient(0deg,#000000,#262626);
      backdrop-filter: blur(10px);
      padding: 25px 105px;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .4);
    }


    input[type=text], select, textarea {
      height:40px;
      width:250px; 
      
      padding: 9px;
      border: 2px solid #fff;
      border-radius: 10px;
      box-sizing: border-box;
      margin-top: 6px;
      margin-bottom: 16px;
      resize: vertical;
      color: #fff;
      
      background: -webkit-gradient(linear,left bottom, left top,from(#000000),to(#262626));
      background: -webkit-linear-gradient(bottom,#000000,#262626);
      background: -moz-linear-gradient(bottom,#000000,#262626);
      background: -o-linear-gradient(bottom,#000000,#262626);
      background: linear-gradient(0deg,#000000,#262626);
      backdrop-filter: blur(10px);
    }


</style>

<div class="card text-center" style="background: rgba(1, 2, 3,0.6); padding: 30px 30px ;">
  <div class="card-header" >
    
     <!-- Button trigger modal -->
      <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalLong" style="margin-top: 10px;">
        Trivia
      </button>

      <br>
      <br>

      <!-- Modal -->
      <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLongTitle">Trivia</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              Oxford Dictionary has 273,000 headwords; 171,476 of them being in current use, 47,156 being obsolete words and around 9,500 derivative words included as subentries.
              <br>
              <b>Out of so many words which word you choose and which you don't choose decides your way ahead.  </b>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
             
            </div>
          </div>
        </div>
      </div>


  </div>
  <div class="card-body" style="color: #fff;">
    <p class="card-text" style="color: #fff;font-family: 'MedievalSharp', cursive;"> Enter a word:</p>

  </div>

  <form action="" class="form"  style="color: white" method="post" id="upload_form" enctype="multipart/form-data" >
    {% csrf_token %}
    <input type="text" name="sample" placeholder="" maxlength="12" minlength="8" required="" id="id_sample">
      <br>
      <input type="submit" value="Submit" style="color: #fff;padding:5px;height:40px;width:100px;border: 2px solid #fff;">
      </form>

      {% if invalid %}
      <h4 style="color: red;">This input is not valid(It should have only alphabets).</h4>

      {% elif repeat %}
      <h4 style="color: red;">This word has already been used....try something else</h4>
      {% elif invalid_variation %}
          <h4 style="color: red;">This input is not valid(It should have some more variation).</h4>
      {% endif %}
{% if wrong %}
  <h4 style="color: red;">Wrong Answer</h4>
{% endif %}
</div>


{% endblock %}

REChase/REChase/prefixSum/templates/prefixSum/question.html
{% include 'teams/base_bootstrap.html' %}


{% block content %}
<link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet">
<link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=MedievalSharp&display=swap" rel="stylesheet">
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Niconne&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Metrophobic&display=swap');

    input[type=submit] {
      background: -webkit-gradient(linear,left bottom, left top,from(#000000),to(#262626));
      background: -webkit-linear-gradient(bottom,#000000,#262626);
      background: -moz-linear-gradient(bottom,#000000,#262626);
      background: -o-linear-gradient(bottom,#000000,#262626);
      background: linear-gradient(0deg,#000000,#262626);
      backdrop-filter: blur(10px);
      padding: 25px 105px;
      border: none;
      border-radius: 10px;
      cursor: pointer;
      box-shadow: 0 0 1rem 0 rgba(0, 0, 0, .4);
    }


    input[type=text], select, textarea {
      height:40px;
      width:250px; 
      
      padding: 9px;
      border: 2px solid #fff;
      border-radius: 10px;
      box-sizing: border-box;
      margin-top: 6px;
      margin-bottom: 16px;
      resize: vertical;
      color: #fff;
      
      background: -webkit-gradient(linear,left bottom, left top,from(#000000),to(#262626));
      background: -webkit-linear-gradient(bottom,#000000,#262626);
      background: -moz-linear-gradient(bottom,#000000,#262626);
      background: -o-linear-gradient(bottom,#000000,#262626);
      background: linear-gradient(0deg,#000000,#262626);
      backdrop-filter: blur(10px);
    }

</style>

<div class="card text-center" style="background: rgba(1, 2, 3,0.6); padding: 30px 30px ;">

  {% if question.modal %}
  <div class="card-header" >

 <!-- Button trigger modal -->
  <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalLong" style="margin-top: 10px;">
    Hints
  </button>
  <br>
  <br>

  <!-- Modal -->
  <div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Hints</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          {{ question.modal | safe }}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>


</div>
{% endif %}

  <div class="card-body" style="color: #fff;">
    <p class="card-text" style="color: #fff;font-family: 'MedievalSharp', cursive;">If {{ sample_name }} is given as <br>
      {{ sample_ans }} <br>
      Then {{ name }} is given as ????<br></p>

  </div>


  <form action="" class="form" method="post" id="upload_form" enctype="multipart/form-data" >
    {% csrf_token %}
      <input type="text" id="subject" name="answer" maxlength="40" placeholder="Your Answer Here.." style="height:40px;width:250px; color: #fff;">
      <br>
      <input type="submit" value="Submit" style="color: #fff;padding:5px;height:40px;width:100px;border: 2px solid #fff;">
  </form>
  {% if wrong %}
    <h4 style="color: red;">Wrong Answer</h4>
  {% endif %}
</div>





{% endblock %}